-- Migration 061: Term-based fee installments
--
-- Allows the bursar to split an annual fee structure into term installments
-- (e.g. $400 total → Term 1 $150 · Term 2 $150 · Term 3 $100).
--
-- Key design decisions:
--   • fee_structure_installments  — bursar defines the split once at the structure level
--   • student_fee_installments    — auto-generated per student when the split is saved
--   • Trigger on student_fees.amount_paid  — redistributes cumulative payments across
--     installments in term_order on every payment, so the payment recording flow is
--     completely unchanged (bursar still just records a payment against the parent fee)
--   • has_installments flag on fee_structures  — drives UI without a subquery

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add has_installments flag to fee_structures
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE fee_structures
  ADD COLUMN IF NOT EXISTS has_installments BOOLEAN NOT NULL DEFAULT FALSE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. fee_structure_installments
--    One row per term per fee structure.  Bursar defines these; they drive
--    the per-student records below.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fee_structure_installments (
  id               UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  school_id        UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  fee_structure_id UUID NOT NULL REFERENCES fee_structures(id) ON DELETE CASCADE,
  term_name        VARCHAR(100) NOT NULL,       -- e.g. "First Term", "Term 1"
  term_order       INT NOT NULL DEFAULT 1,      -- sort order; 1 = first term
  amount_usd       DECIMAL(10,2) NOT NULL CHECK (amount_usd > 0),
  due_date         DATE NOT NULL,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(fee_structure_id, term_name)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. student_fee_installments
--    One row per term per student fee.  Auto-generated by the RPC below.
--    Statuses are maintained by the trigger in section 6.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS student_fee_installments (
  id                           UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  school_id                    UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
  student_id                   UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  student_fee_id               UUID NOT NULL REFERENCES student_fees(id) ON DELETE CASCADE,
  fee_structure_installment_id UUID NOT NULL REFERENCES fee_structure_installments(id) ON DELETE CASCADE,
  term_name                    VARCHAR(100) NOT NULL,
  term_order                   INT NOT NULL,
  amount_due                   DECIMAL(10,2) NOT NULL,
  amount_paid                  DECIMAL(10,2) NOT NULL DEFAULT 0,
  balance                      DECIMAL(10,2) NOT NULL,
  status                       VARCHAR(50) NOT NULL DEFAULT 'pending',
  due_date                     DATE NOT NULL,
  created_at                   TIMESTAMPTZ DEFAULT NOW(),
  updated_at                   TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(student_fee_id, fee_structure_installment_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Row-Level Security
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE fee_structure_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_fee_installments   ENABLE ROW LEVEL SECURITY;

-- Staff see/write their school's fee_structure_installments
CREATE POLICY "fsi_school_staff"
  ON fee_structure_installments FOR ALL TO authenticated
  USING (school_id = (SELECT school_id FROM users WHERE auth_id = auth.uid() LIMIT 1))
  WITH CHECK (school_id = (SELECT school_id FROM users WHERE auth_id = auth.uid() LIMIT 1));

-- Students + staff can SELECT student_fee_installments
CREATE POLICY "sfin_read"
  ON student_fee_installments FOR SELECT TO authenticated
  USING (
    -- student seeing their own
    student_id = auth_student_id()
    OR
    -- staff seeing their school
    school_id = (SELECT school_id FROM users WHERE auth_id = auth.uid() LIMIT 1)
  );

-- Only staff (not students) can write student_fee_installments
CREATE POLICY "sfin_staff_write"
  ON student_fee_installments FOR ALL TO authenticated
  USING (school_id = (SELECT school_id FROM users WHERE auth_id = auth.uid() LIMIT 1))
  WITH CHECK (school_id = (SELECT school_id FROM users WHERE auth_id = auth.uid() LIMIT 1));

-- Service role full access (used by trigger and RPC)
CREATE POLICY "fsi_service_role"
  ON fee_structure_installments FOR ALL TO service_role
  USING (true) WITH CHECK (true);

CREATE POLICY "sfin_service_role"
  ON student_fee_installments FOR ALL TO service_role
  USING (true) WITH CHECK (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. RPC: create_fee_installments
--    Called by the bursar when saving a term split for a fee structure.
--    • Validates that sum(installments) ≤ fee amount
--    • Replaces any existing installment definition (idempotent)
--    • Auto-generates student_fee_installments for every student who already
--      has a student_fees record for this fee structure
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION create_fee_installments(
  p_fee_structure_id UUID,
  p_school_id        UUID,
  p_installments     JSONB   -- [{term_name, term_order, amount_usd, due_date}, ...]
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  total_alloc  DECIMAL(10,2);
  fee_total    DECIMAL(10,2);
  inst         JSONB;
  new_fsi_id   UUID;
BEGIN
  -- Validate: sum of installment amounts must not exceed the fee structure total
  SELECT COALESCE(SUM((val->>'amount_usd')::DECIMAL), 0)
  INTO   total_alloc
  FROM   jsonb_array_elements(p_installments) val;

  SELECT amount_usd INTO fee_total
  FROM   fee_structures
  WHERE  id = p_fee_structure_id;

  IF fee_total IS NULL THEN
    RAISE EXCEPTION 'Fee structure % not found', p_fee_structure_id;
  END IF;

  IF total_alloc > fee_total + 0.01 THEN
    RAISE EXCEPTION
      'Total installment amounts ($%) exceed fee amount ($%)',
      total_alloc, fee_total;
  END IF;

  -- Delete existing structure installments (ON DELETE CASCADE removes student records too)
  DELETE FROM fee_structure_installments
  WHERE  fee_structure_id = p_fee_structure_id;

  -- Insert new structure installments and generate per-student records
  FOR inst IN SELECT * FROM jsonb_array_elements(p_installments)
  LOOP
    INSERT INTO fee_structure_installments (
      school_id, fee_structure_id, term_name, term_order, amount_usd, due_date
    ) VALUES (
      p_school_id,
      p_fee_structure_id,
      inst->>'term_name',
      (inst->>'term_order')::INT,
      (inst->>'amount_usd')::DECIMAL,
      (inst->>'due_date')::DATE
    )
    RETURNING id INTO new_fsi_id;

    -- Generate per-student installment records for every student with this fee
    INSERT INTO student_fee_installments (
      school_id,
      student_id,
      student_fee_id,
      fee_structure_installment_id,
      term_name,
      term_order,
      amount_due,
      amount_paid,
      balance,
      status,
      due_date
    )
    SELECT
      sf.school_id,
      sf.student_id,
      sf.id,
      new_fsi_id,
      inst->>'term_name',
      (inst->>'term_order')::INT,
      (inst->>'amount_usd')::DECIMAL,
      -- Distribute any already-paid amount across installments in order
      -- (handles the case where installments are added after partial payment)
      0,
      (inst->>'amount_usd')::DECIMAL,
      'pending',
      (inst->>'due_date')::DATE
    FROM   student_fees sf
    WHERE  sf.fee_structure_id = p_fee_structure_id
    ON CONFLICT (student_fee_id, fee_structure_installment_id) DO NOTHING;
  END LOOP;

  -- Mark the fee structure as split into installments
  UPDATE fee_structures
  SET    has_installments = TRUE
  WHERE  id = p_fee_structure_id;

  -- Sync installment statuses with any payments already recorded
  -- (runs the same logic as the trigger below for all affected student fees)
  PERFORM sync_single_student_fee_installments(sf.id)
  FROM    student_fees sf
  WHERE   sf.fee_structure_id = p_fee_structure_id
    AND   sf.amount_paid > 0;
END;
$$;

GRANT EXECUTE ON FUNCTION create_fee_installments TO authenticated;
GRANT EXECUTE ON FUNCTION create_fee_installments TO service_role;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Helper: sync_single_student_fee_installments
--    Distributes a student_fees.amount_paid across installments in term_order.
--    Called by both the trigger and the RPC above.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION sync_single_student_fee_installments(p_student_fee_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  remaining DECIMAL(10,2);
  inst      RECORD;
BEGIN
  SELECT amount_paid INTO remaining
  FROM   student_fees
  WHERE  id = p_student_fee_id;

  FOR inst IN
    SELECT * FROM student_fee_installments
    WHERE  student_fee_id = p_student_fee_id
    ORDER  BY term_order ASC
  LOOP
    IF remaining >= inst.amount_due THEN
      UPDATE student_fee_installments SET
        amount_paid = inst.amount_due,
        balance     = 0,
        status      = 'paid',
        updated_at  = NOW()
      WHERE id = inst.id;
      remaining := remaining - inst.amount_due;

    ELSIF remaining > 0 THEN
      UPDATE student_fee_installments SET
        amount_paid = remaining,
        balance     = inst.amount_due - remaining,
        status      = 'partial',
        updated_at  = NOW()
      WHERE id = inst.id;
      remaining := 0;

    ELSE
      UPDATE student_fee_installments SET
        amount_paid = 0,
        balance     = inst.amount_due,
        status      = CASE
                        WHEN inst.due_date < CURRENT_DATE THEN 'overdue'
                        ELSE 'pending'
                      END,
        updated_at  = NOW()
      WHERE id = inst.id;
    END IF;
  END LOOP;
END;
$$;

GRANT EXECUTE ON FUNCTION sync_single_student_fee_installments TO authenticated;
GRANT EXECUTE ON FUNCTION sync_single_student_fee_installments TO service_role;

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Trigger: sync installment statuses on every payment
--    Fires AFTER UPDATE OF amount_paid on student_fees.
--    The existing record_fee_payment RPC and bursarService.recordPayment()
--    both update student_fees.amount_paid — this trigger propagates the
--    change to installments automatically, so payment recording is unchanged.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION trg_sync_fee_installment_statuses()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Only run if this student_fee has installments
  IF EXISTS (
    SELECT 1 FROM student_fee_installments WHERE student_fee_id = NEW.id
  ) THEN
    PERFORM sync_single_student_fee_installments(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_fee_installment_statuses ON student_fees;

CREATE TRIGGER trg_sync_fee_installment_statuses
  AFTER UPDATE OF amount_paid ON student_fees
  FOR EACH ROW
  WHEN (OLD.amount_paid IS DISTINCT FROM NEW.amount_paid)
  EXECUTE FUNCTION trg_sync_fee_installment_statuses();
